### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by kensupermen**
Rebase all feature

### CODE REVIEW

**Comment by coderschoolreview** [comment]
@kensupermen not sure why our previous review isn't visible here.. but anyway thanks for the submission.

### Next step

Let's schedule a quick call to confirm that this course is a right fit for you. 
We also would like to know a little more about your experience. 
Please book a slot from [here](https://calendly.com/harley/15m).

**Comment by coderschoolreview** [comment]
Hi @kensupermen, sorry for unexpected incident with the previous review from us. Thanks for your hard work, you've done a good job so far. This is some feedback from us: 

## Great things: 
- You've done all required features
- You've added almost all required (except the article view-count)
- Clean and clear README file, as well as Walkthrough.gif
- You listed many additional features you wanna add. 

## Suggestion: 
- It's great to follow a good Ruby code style. We recommend this: 
[Ruby Style Guide](https://github.com/github/rubocop-github/blob/master/STYLEGUIDE.md)
- You should use bootstrap form-group class for your forms (Commenting, Posting)
- Style flash alerts in bootstrap style. Instead of `<p id="notice">Article was successfully destroyed.</p>`, consider rendering it as `<div class="alert alert-success">Article was successfully destroyed.</div>`. [Here](https://gist.github.com/suryart/7418454)'s an example of how to do it.
- Links on your page will turn to black when hovering on it due to conflict of boostrap 4 with scaffold style. You can remove `scaffolds.scss` file to solve this.
- Last but not least, you should have validation in your model to prevent user input wrong/empty record. This is sample: 

```ruby 
# article.rb
validates :title, :body, presence: true
# comment.rb
validates :message, presence: true
```

You can continue improve your app and request us to review it again anytime, we love to see your progress has been improve day by day. It would be great if you can implement all additional features as you listed. 

And if haven't take an interview with us , please book a slot from [here](https://calendly.com/harley/15m). We would like to confirm that this course is a right fit for you and also to know a little more about your experience.

**Comment by coderschoolreview** [comment]
@kensupermen can you make some changes by on our suggestions? We have many good submissions this time. For you to be accepted, I'd still like to see that you can improve upon our feedback :)

**Comment by kensupermen** [comment]
@coderschoolreview  Thanks for you suggest.
I submitted at master branch follow your suggest.

**Pull request merged**
